### ISSUE TITLE
Documentation for v0.6.0

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#490]
- [x] Update the [website](http://txtuml.inf.elte.hu/wiki/doku.php?id=v060:release). (@djnemeth)
- [x] Update the [user guide](http://txtuml.inf.elte.hu/wiki/doku.php?id=v060:userguide). (#464, #452, #479, #476, #439) 
- [x] Update the [language guide](http://txtuml.inf.elte.hu/wiki/doku.php?id=v060:language). (#447, #485)
- [x] Update the [diagram language guide](http://txtuml.inf.elte.hu/wiki/doku.php?id=v060:layout). (#481)
- [x] Export and upload the [JtxtUML API documentation](http://txtuml.inf.elte.hu/releases/txtuml-v060/api/). (#488) (@kovacsgabor)
- [x] Export and upload the C++ runtime documentation. (#498) (@nagyandras95)
- [x] Export and upload the demo models. (#489) (@djnemeth)

**Comment by djnemeth** [comment]
Please let me know if I missed anything affecting the documentation.

**Comment by kovacsgabor** [comment]
About model enums: As they are currently not fully supported (they are not exported), I think they should not appear in the documentation.
